# fly.toml app configuration file generated for rest-api-cars-divine-wildflower-8002 on 2025-09-19T00:20:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rest-api-cars-divine-wildflower-8002'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[deploy]
  release_command = 'npm run setup'