name: CI CD Lengkap Sekali
on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install
              run: npm ci
            - name: Create .env file
              run: |
                  touch .env
                  echo CLIENT=pg >> .env
                  echo DATABASE_URL=postgres://postgres:o2p3unETPVQnAVn@rest-api-cars-db.flycast:5432/binar_car_rental?schema=public >> .env
            - name: Create Private Key
              run: npm run keys
            - name: Migrate database and Seed
              run: npx knex migrate:down --knexfile src/config/knexfile.ts && npx knex migrate:latest --knexfile src/config/knexfile.ts && npx knex seed:run --knexfile src/config/knexfile.ts
            - name: Test Coverage
              run: npm run coverage
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
